import DateJs from './index.js';
document.write(DateJs(new Date()).format('YY-MM-DD'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY-MM-DD'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY-MM-DD hh:mm:ss'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY-MM-DD hh:mm:ss:SS'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY-MM-DD hh:mm:ss:SSS'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY/MM/DD'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY/MM/DD hh:mm:ss'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY/MM/DD hh:mm:ss'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY/MM/DD hh:mm:ss:SS'))
document.write('<br/>')
document.write(DateJs(new Date()).format('YYYY/MM/DD hh:mm:ss:SSS'))
document.write('<br/>')
document.write(DateJs(new Date()).toZone().format('YYYY/MM/DD hh:mm:ss:SSS'))
document.write('<br/>')
document.write(DateJs(new Date()).toZone().stamp())
document.write('<br/>')
document.write(DateJs(new Date()).$Y)
